name: 'dagger'

on:
  push:
    branches:
    - main

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21'
      -
        name: Install Dagger CLI
        run: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }
      -
        name: Run tests with dagger
        run: dagger run --workdir ./db-service/ go run main.go
